version: 2

sources:
  - name: tpch
    database: playground
    schema: tpch  
    tables:
      - name: orders_bronze
        columns:
              - name: O_ORDERKEY
                description: Primary key of the orders table
                tests:
                  - unique
                  - not_null
      - name: customer_bronze
        columns:
            - name: C_CUSTKEY
              description: Primary key of the customer table
              tests:
                - unique
                - not_null
      - name: lineitem_bronze
        columns:
              - name: L_ORDERKEY
                description: Primary key of the lineitem table
                tests:
                  - unique:
                      config:
                        severity: warn
                  - not_null
  - name: weerdata
    config:
      freshness: # changed to config in v1.9
        warn_after:
          count: 1
          period: minute  
    database: playground
    schema: dbt_ericmuhren
    tables:
      - name: weerdata_gilze_rijen
